### ISSUE TITLE
Config file not created with .php extension when publishing package configuration

### ISSUE THREAD

**Issue by ghost** [kevindierkx/laravel-domain-parser#14]
### Bug Report

_(Fill in the relevant information below to help triage your issue.)_

| Information | Description |
|--------------|---------|
| Version | 0.5.0 |
| PHP version |  7.4.8 |
| OS Platform | Both Windows 10 and CentOS 7  |

#### Summary

Config file is created but it is missing .php extension when running php artisan vendor:publish --provider="Bakame\Laravel\Pdp\ServiceProvider" --tag=config

#### Standalone code, or other way to reproduce the problem

Simply install the package and attempt to publish the config file

#### Expected result

Config file should have .php extension

#### Actual result

Config file has no file extension

**Comment by kevindierkx** [comment]
@dougfelton Thanks for the report! I've tagged a new version (0.5.1) which should resolve the problem.

If I may ask, what exactly are you changing in the configuration file?
I'm planning to drop some configurations in an upcomming release, it would be super helpfull if you could share your experiences!

**Comment by ghost** [comment]
@kevindierkx I haven't edited the configuration at all (aside from adding the .php extension).

If you're at all curious, I'm using your package to help with email validation.  In my Laravel app, I've been getting a lot of email submissions which end in @gmail.con (for example) and the built-in email validator has no problem with that.  So I am using your package's Rules Facade in a custom validation rule I created.  It's working great, and I really appreciate the work you put in on this package.

**Comment by kevindierkx** [comment]
@dougfelton Thanks for the insight! That's actually a great idea for email validation...

Fyi: If you don't plan to change anything in the configuration you could actually skip the publishing step or remove the published config from your config dir.
