### ISSUE TITLE
Expose registrableDomain()

### ISSUE THREAD

**Issue by khavishbhundoo** [kevindierkx/laravel-domain-parser#16]
### Feature Request
Hi,

It would be great if `registrableDomain()` and `subDomain()` and other useful methods can be exposed via a Facade so that laravel users can migrate to `laravel-domain-parser` instead of `php-domain-parser`

**Comment by kevindierkx** [comment]
Hey @khavishbhundoo 

That's exactly what this package tries to solve!

Laravel  domain parser can be seen as a bridge package for pdp, it offers various bindings with the [Laravel IOC container](https://laravel.com/docs/8.x/container) which expose the various functionalities of PDP. In addition it implements the Laravel cache out of the box for caching purposes and supplies a command for updating the cache. Please refer to [#Maintenance](https://github.com/kevindierkx/laravel-domain-parser#maintenance) for more information.

For example you can use the `\Bakame\Laravel\Pdp\Facades\Rules` and `\Bakame\Laravel\Pdp\Facades\TopLevelDomains` facades to access an instance of `\Pdp\PublicSuffixList` and `\Pdp\TopLevelDomainList` respectively.

Using the following should give you access to the registerable domain:

```php
use Bakame\Laravel\Pdp\Facades\TopLevelDomains;

echo TopLevelDomains::resolve('distortedfusion.com')->registrableDomain()->toString();

// distortedfusion.com
```

I'm not planning to add a Laravel like API on top of the existing PDP API. Feel free to comment if you have any further questions. I'll leave this issue open for now to let others chime in.

**Comment by khavishbhundoo** [comment]
Thanks @kevindierkx for the detailed explanation and example.

Just my 2 cents : There is a typo in your example, should be `registrableDomain()` rather than `registerableDomain()` . `TopLevelDomains::resolve` could be `\TopLevelDomains::resolve`
