### ISSUE TITLE
Support for Laravel 6.x/7.x

### ISSUE THREAD

**Issue by kevindierkx** [kevindierkx/laravel-domain-parser#2]
Support for Laravel 6.x has already been proposed in: https://github.com/bakame-php/laravel-domain-parser/pull/1

For future support of Larvel 7.x and up I would suggest dropping support for older Laravel versions in future versions of this package. This would make testing a bit easier. I was playing around in the previously mentioned PR to support L5.x up till L7.x, but that resulted in the need of supporting 3 different versions of various testing packages and resulted in various errors related to them.

By removing L5.x we could up the PHP version requirement to 7.2, this is the minimal requirement of L6.x and update PHPStan to a more recent version.

**Comment by nyamsprod** [comment]
I have no objection in deprecated old laraval versions as long as they can match the currently stable version with ease.

**Comment by nyamsprod** [comment]
@kevindierkx I can't transfer the library to you as long as you have a fork on your account. Please delete your fork then I'll transfer the repo to you 😉

**Comment by kevindierkx** [comment]
@nyamsprod done!
