### ISSUE TITLE
Laravel 9.x: Installation failed because psr/simple-cache must be ^3.0

### ISSUE THREAD

**Issue by web-ruslan** [kevindierkx/laravel-domain-parser#21]
### Bug Report

| Information | Description |
|--------------|---------|
| Laravel | 9 |
| Version | [1.1.0](https://packagist.org/packages/bakame/laravel-domain-parser#1.1.0) |
| PHP version | 8.1.3 |
| OS Platform | Ubuntu 20.04 |

#### Summary

Installation failed because psr/simple-cache must be ^3.0

#### Standalone code, or other way to reproduce the problem

`sail composer require bakame/laravel-domain-parser`

#### Expected result

Laravel package install

#### Actual result

Info from https://repo.packagist.org: #StandWithUkraine
Using version ^1.1 for bakame/laravel-domain-parser
./composer.json has been updated
Running composer update bakame/laravel-domain-parser
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires bakame/laravel-domain-parser ^1.1 -> satisfiable by bakame/laravel-domain-parser[1.1.0, 1.x-dev].
    - bakame/laravel-domain-parser[1.1.0, ..., 1.x-dev] require psr/simple-cache ^1.0 -> found psr/simple-cache[1.0.0, 1.0.1] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require bakame/laravel-domain-parser:*" to figure out if any version is installable, or "composer require bakame/laravel-domain-parser:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by web-ruslan** [comment]
I created pull request to fix this bug

**Comment by kevindierkx** [comment]
Thank you! I've tagged the `1.1.1` release including these changes.
