### ISSUE TITLE
compatibility with Laravel 9 and php8... 

### ISSUE THREAD

**Issue by Mr-HAP** [kevindierkx/laravel-domain-parser#27]
Hello good morning, I made an upgrade to php8 and laravel 9 and now I'm getting some errors ....

|    Q        |   A
|------------ | ------
| Version     | 1.1.1

### Question

the error are:
`Bakame\Laravel\Pdp\DomainParser::convertTtlToDateTime(): Argument #1 ($ttl) must be of type ?int, string given, called in /home/admin/domains/digidip.local/vendor/bakame/laravel-domain-parser/src/DomainParser.php on line 44  `

In DomainParserConfig.php line 16:
`  Cannot assign string to property Bakame\Laravel\Pdp\DomainParserConfig::$cacheTtl of type ?int `

Do you know how I can fix it? I don't know what I'm doing wrong.
regards

**Comment by kevindierkx** [comment]
@Mr-HAP Can you show me your code snippet producing this error?

**Comment by Mr-HAP** [comment]
hello, 
the error is not in my code...
```
<?php

namespace Bakame\Laravel\Pdp;

class DomainParserConfig
{
    public ?string $cacheDriver = null;
    public ?int $cacheTtl = null;
    public array $httpClientOptions;
    public ?string $uriPublicSuffixList;
    public ?string $uriTopLevelDomainList;

    public function __construct(array $properties)
    {
        $this->cacheDriver = $properties['cache_driver'] ?? null;
        $this->cacheTtl = $properties['cache_ttl'] ?? null;
        $this->httpClientOptions = $properties['http_client_options'] ?? [];
        $this->uriPublicSuffixList = $properties['uri_public_suffix_list'] ?? null;
        $this->uriTopLevelDomainList = $properties['uri_top_level_domain_list'] ?? null;
    }
} 
```
is in the library 
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/26280252/220356791-93dfd607-4a40-45f4-9af3-2d88d2d7e9f1.png">

**Comment by kevindierkx** [comment]
@Mr-HAP Please check you config file, as the error states the `cache_ttl` value in the `domain-parser.php` file should either be an integer or null.

**Comment by Mr-HAP** [comment]
thanks now is working.
before i had "1 DAY" now i change for secs
