### ISSUE TITLE
Support Laravel 10

### ISSUE THREAD

**Issue by onlime** [kevindierkx/laravel-domain-parser#28]
Just creating this issue so that you're aware that there's interest. We rely on your fantastic package for one of our projects, and this is one of the very last packages that don't support Laravel 10 yet.

Please also drop PHP 7.4/8.0 support, as Laravel 10 minimum required version is PHP 8.1.

**Comment by onlime** [comment]
just to let you know I have tested Laravel Shift's #26, confirming it working

**Comment by kevindierkx** [comment]
L10 Support has been added in ^1.2
