### ISSUE TITLE
Fix packagist.org updates

### ISSUE THREAD

**Issue by kevindierkx** [kevindierkx/laravel-domain-parser#4]
Due to the recent ownership transfer, packagist.org doesn't seem to handle the repository updates correctly.

@nyamsprod Could you help me out? I don't have access to the packagist package/entry.

**Comment by nyamsprod** [comment]
Yes let me check I may have to add you to the list of maintainers I think. Then you can do the rest.

**Comment by nyamsprod** [comment]
Done you should have maintainance power over on packagist.org now

**Comment by kevindierkx** [comment]
Thanks! The updates are working again.
