### ISSUE TITLE
Upgrade jeremykendall/php-domain-parser to latest stable 6.x and drop support for older PHP versions

### ISSUE THREAD

**Issue by kevindierkx** [kevindierkx/laravel-domain-parser#6]
~We're currently still dependant on `jeremykendall/php-domain-parser:^5.4`, the latest stable is `^5.7`. To further futureproof this package this should be upgraded.~

---

Slight change of plans, now that `jeremykendall/php-domain-parser:^6.0` has been released.
This release also introduced support for PHP 8.x and according to the changelog dropped or will drop support for PHP 7.4.

This requires some refactoring related to the changes in the base package: [Please refer to the changelog](https://github.com/jeremykendall/php-domain-parser/blob/develop/CHANGELOG.md#600---2020-12-13)

In result, creating a new release using `jeremykendall/php-domain-parser:^6.0` will drop support for PHP 7.4 aswell. So the new target for a next release is PHP8.x with L8.x support dropping al previous versions.

@cfroystad already proposed a PR for L8.x support using the old base package, this will be merged in an intermediate release discussed here: #9

**Comment by nyamsprod** [comment]
@kevindierkx Just a heads up to let you know that I started to work on the next major version of this library for more info you can check the current [changelog](https://github.com/jeremykendall/php-domain-parser/blob/feature/v6/CHANGELOG.md#6xx---tbd) 

While most of the features remain the same, the big difference is:

- it drop support for anything before PHP7.4;
- Managing the external database has been completely revamped;

IMHO v6 will be easier to integrate in Laravel 8 with the new `Pdp\Storage\PsrStorageFactory` But I'll let you be the judge of that 😉 .

Also the documentation is not yet finish but I hope that by looking at the code you'll get a good sense of where the package is heading. 

Any how feel free to drop some lines if you find missing features you would like added. Now is the perfect time because I want to release this one before PHP8 or at the same time 😉

**Comment by kevindierkx** [comment]
@nyamsprod Thanks for the heads up!

Looking at the supported PHP version in Laravel 8.x it might be better to have support for pdp 5.7.x and in a later release drop support for pdp 5.x altogether... Not sure yet.

I'll just assume that Laravel 9.x would still have support for php 7.4, so an intermediate release utilising pdp 6.x wouldn't be a bad idea.

**Comment by nyamsprod** [comment]
Good news, bad news... V6 is around the corner... I try hard to reduce BC but the more I was coding the harder it became. So while I try to keep the API as compatible as possible many changes had to be introduce but I still think the new API is more DX friendly and is better future proof. I've added an upgrading file to list the BC breaks.

**Comment by nyamsprod** [comment]
PHP domain parser V6 has been released 🎉

**Comment by kevindierkx** [comment]
> PHP domain parser V6 has been released 🎉

Awesome! I've made some updates to the issue to reflect the change of plans for this package.

**Comment by pmochine** [comment]
Can't wait for this update!

**Comment by brunogaspar** [comment]
Hello guys

Is this something that will still be worked on?

I see that there's a `pdp6` branch, can i help somehow moving it forward?

**Comment by kevindierkx** [comment]
@brunogaspar Hey! I'm still maintaining this package. The pdp6 branch is mostly complete, but still requires some testing before I'm comfortable merging it with master. I didn't find the time to do that yet unfortunatly.

However, the pdp6 branch should be ready to use and I'm not planning to make any big changes to it anymore before release. If you would you like it would be a great help if you could quickly glance over it and check if I've missed something.

**Comment by brunogaspar** [comment]
Sure. I'll install that branch on this project i have and see how it goes.

Will keep you updated :)

**Comment by nyamsprod** [comment]
@kevindierkx quick question was adapting the package to v6 complex ? Is there an public API change that would have simplify more the migration ?

**Comment by kevindierkx** [comment]
@nyamsprod The hardest part is understanding when to use Rules or TopLevelDomains. If I remember correctly I've had some issues with the to_unicode and to_ascii directives this package offers,  but that wasn't related to the public API.

The removal of the storage system wasn't such a big problem. The implementation of the Laravel Framework can be a bit limiting in this regard and made it simpler for me to simply drop some options from the config.

Overal the upgrade to PDP6 was rather straight forward.

---

@pmochine @brunogaspar As you've might have noticed I've just released v1.0.0 of this package. Al breaking changes have been mentioned in the [upgrading guide](https://github.com/kevindierkx/laravel-domain-parser/blob/master/UPGRADING.md)
